### PR TITLE
Added Google Auth

### PR DESCRIPTION
**Pull request by Pr0gramad0r**
Added Google Auth. Also commented your things out so it easier for me to add the things. So just uncomment

### CODE REVIEW

**Comment by Pr0gramad0r** [comment]
Made separate files for AUTH and firestore

**Review by boriskrisanov — COMMENTED** [review]
I will test this when I get home. Looks good though!

**Comment by Pr0gramad0r** [comment]
Also added a nav bar

**Review by Pr0gramad0r — COMMENTED** [review]
Very good

**Review by boriskrisanov — CHANGES_REQUESTED** [review]
Please use jQuery instead of regular DOM functions. For example, use `$("#whenSignedOut");` instead of `document.getElementById('whenSignedOut');`

**Comment by Pr0gramad0r** [comment]
The `Fixed Some Stupid Thing` Commit is just me fixing because I forgot to add semi colons

**Pull request merged**
